# This is my first, very own configuration file for yamllint!
# It extends the default conf by adjusting some options.

extends: default

rules:
  line-length:
    max: 200
    level: warning

  document-start: disable
  indentation: disable
  comments: disable
  truthy: disable
