name: Container Pipeline Tester
on:
  workflow_dispatch:
    inputs:
      group_dir:
        required: true
        description: 'Enter Container Group Directory (docker/flex-gpu, docker/max-gpu, etc.):'
        type: string
      env_overrides:
        description: 'Enter Bash Env Variable Overrides in `KEY=VAL KEY2=VAL2` format:'
        required: false
        type: string
  pull_request:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-build-matrix:
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    runs-on: [ 'k8-runners' ]
    env:
      # excluding from the build due to issues: ["docker/max-gpu", "tf-cpu"]
      DEFAULT_GROUPS: '["docker/dataset", "docker/flex-gpu", "docker/pyt-cpu", "docker/cuda-gpu"]'
    steps:
      - uses: actions/checkout@v4
      - name: Set Matrix
        id: matrix
        run: |
          echo "matrix=$(echo '${{ inputs.group_dir || env.DEFAULT_GROUPS }}' | jq -c .)" >> $GITHUB_OUTPUT
      - name: Print Inputs
        if: ${{ inputs.env_overrides }}
        run: echo "Overrides - ${{ inputs.env_overrides }}" >> $GITHUB_STEP_SUMMARY

  build-containers:
    needs: [ setup-build-matrix ]
    container:
      image: ${{ vars.REGISTRY }}/aiops/compose-dev
      env:
        http_proxy: ${{ secrets.HTTP_PROXY }}
        https_proxy: ${{ secrets.HTTPS_PROXY }}
        no_proxy: ${{ secrets.NO_PROXY }}
      credentials:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
      volumes:
        - /usr/local/share/ca-certificates/:/usr/local/share/ca-certificates/
    runs-on: [ 'builder' ]
    strategy:
      matrix:
        group: ${{ fromJson(needs.setup-build-matrix.outputs.matrix) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Print registry and docker version
        run: |
          echo ${{ vars.REGISTRY }}
          docker --version
          docker compose version
      - name: Setup Intel Certificates
        run: update-ca-certificates --fresh
      - name: Build Container Group
        uses: intel-innersource/frameworks.ai.infrastructure.machine-learning-operations/.github@develop
        with:
          registry: ${{ vars.REGISTRY }}
          group_dir: ${{ matrix.group }}
          env_overrides: ${{ inputs.env_overrides }}
          no-push: true
