name: Model Zoo Workload Tests Performance
on:
  workflow_call:
jobs:
  grafana:
    runs-on: [self-hosted, gasp]
    outputs:
      md-tables: ${{ steps.get-tables.outputs.MD_TABLES }}
    container:
      image: amr-registry.caas.intel.com/aiops/mlops:ubuntu-22.04
      env:
        http_proxy: ${{ secrets.HTTP_PROXY }}
        https_proxy: ${{ secrets.HTTPS_PROXY }}
        no_proxy: ${{ secrets.NO_PROXY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install python3-pip jq -y
        pip install pandas tabulate
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: workload-performances
        path: .github/utils/performances
    - name: Get Tables
      id: get-tables
      shell: bash
      run: |
        cd .github/utils
        python3 create-md-table.py
        MD_TABLES_ARRAY=(*.md)
        MD_TABLES=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${MD_TABLES_ARRAY[@]}")
        echo "MD_TABLES=${MD_TABLES}" >> $GITHUB_OUTPUT
    - name: Send results to Grafana
      uses: intel-innersource/frameworks.ai.platform.mt-whitney-validation/.github/actions/database-uploader@main
      with:
        db_user: tester
        db_table: wl_perf_mz
        db: resultsdb
        file: .github/utils/result_summary_table.json
      env:
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_SERVER: ${{ secrets.DB_SERVER }}
  display-tables:
    needs: grafana
    runs-on: [self-hosted, gasp]
    container:
      image: amr-registry.caas.intel.com/aiops/mlops:ubuntu-22.04
      env:
        http_proxy: ${{ secrets.HTTP_PROXY }}
        https_proxy: ${{ secrets.HTTPS_PROXY }}
        no_proxy: ${{ secrets.NO_PROXY }}
    strategy:
      matrix:
        table: ${{ fromJson(needs.grafana.outputs.md-tables) }}
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install python3-pip -y
        pip install pandas tabulate
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: workload-performances
        path: .github/utils/performances
    - name: Get Tables
      id: get-tables
      shell: bash
      run: |
        cd .github/utils
        python3 create-md-table.py
        MD_TABLE=$(cat ${{ matrix.table }})
        echo "## Performance Tests ${{ matrix.table }}" >> $GITHUB_STEP_SUMMARY
        echo "${MD_TABLE}" >> $GITHUB_STEP_SUMMARY
