name: PR validations
on:
  pull_request:
permissions: read-all
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  checks_setup:
    name: Setup checks
    # TODO: remove condition to enable the job for all pull requests
    if: startsWith(github.head_ref, 'lreal/')
    runs-on: k8-runners
    outputs:
      checks: ${{ steps.set_checks.outputs.checks }}
    steps:
      - uses: actions/checkout@v4
      - name: Analize changed files
        id: set_checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          echo "checks=`python3 .github/utils/pr-checks-setup.py
                                -c .github/config/compliance-config.json
                                -u ${{ github.event.pull_request.url }}`" >> $GITHUB_OUTPUT
      - name: Print checks information
        run:
          echo ${{ toJson(steps.set_checks.outputs.checks) }} | jq
  bom_changes:
    name: BoM changes found
    needs: checks_setup
    runs-on: k8-runners
    if: ${{ fromJson(needs.checks_setup.outputs.checks).flags.is_bom_change }}
    steps:
      - name: Call BoM change action
        run:
          python3 .github/utils/comment-bom-changes.py
                  -u ${{ github.event.pull_request.url }}
                  -j ${{ fromJson(needs.checks_setup.outputs.checks).files.bom }}
  models_check:
    name: Models workloads
    needs: checks_setup
    runs-on: k8-runners
    if: ${{ fromJson(needs.checks_setup.outputs.checks).flags.is_model_change }}
    strategy:
      matrix:
        workload: ${{ fromJson(needs.checks_setup.outputs.checks).dirs.workloads_to_run }}
    steps:
      - name: Workload test execution
        run: echo "Place holder for ${{ matrix.workload }} workload execution"
  containers_check:
    name: Containers building
    needs: checks_setup
    runs-on: k8-runners
    if: ${{ fromJson(needs.checks_setup.outputs.checks).flags.is_container_change }}
    strategy:
      matrix:
        container: ${{ fromJSON(needs.checks_setup.outputs.checks).dirs.containers_to_check }}
    steps:
      - name: Workload test execution
        run: echo "Place holder for ${{ matrix.container }} container building"
