name: Scanner-Snyk
on:
  workflow_dispatch:
    inputs:
      repos:
        description: 'Enter the intel-innersource Project repo name:'
        type: string
        required: true
        default: frameworks.ai.models.intel-models
      refs:
        description: 'Enter Project branch, tag:'
        required: true
        type: string
        default: develop
      scan_type:
        description: 'Scan type for Snyk'
        required: false
        type: string
        default: monitor
      snyk_org:
        description: 'Enter synk org: (eg- iags_mlp)'
        required: true
        type: string
        default: iags_mlp
      runner_label:
        description: 'Enter one label of the runner that will execute the workflow (gasp will not work):'
        required: true
        type: string
        default: k8-runners

jobs:
  scan-snyk:
    uses: intel-innersource/frameworks.ai.infrastructure.code-scan-tools/.github/workflows/Scanner_Snyk_Project_Repo.yml@one-ci-cd
    with:
      repos: ${{ inputs.repos }}
      refs: ${{ inputs.refs }}
      scan_type: ${{ inputs.scan_type }}
      snyk_org: ${{ inputs.snyk_org }}
      runner_label: ${{ inputs.runner_label }}
    secrets:
      SNYK_API_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
      token: ${{ secrets.GITHUB_TOKEN }}
