name: Scans
on:
  workflow_call:

jobs:
  scan-coverity:
    uses: intel-innersource/frameworks.ai.infrastructure.code-scan-tools/.github/workflows/Scanner_Coverity.yml@one-ci-cd
    with:
      org: intel-innersource
      repo: frameworks.ai.models.intel-models
      refs: ${{ github.head_ref }}
      projectType: python
      url: https://coverityent.devtools.intel.com/prod8
      stream: model_zoo_first_test
      runners: "[ 'k8-runners' ]"
    secrets:
      USER: tf_qa_prod
      PASSWORD: ${{ secrets.TF_QA_PROD }}
      token: ${{ secrets.GITHUB_TOKEN }}
