name: Model Zoo Notebook Test
on:
  workflow_dispatch:

jobs:
  manual-tl-notebook-test:
    runs-on: [aia-mlops]
    container:
      image: ${{ vars.REGISTRY }}/aiops/compose-dev
      options: --shm-size=8GB
      #credentials:
      #  username: ${{ secrets.REGISTRY_USER }}
      #   password: ${{ secrets.REGISTRY_TOKEN }}
      env:
        http_proxy: ${{ secrets.HTTP_PROXY }}
        https_proxy: ${{ secrets.HTTPS_PROXY }}
        no_proxy: ${{ secrets.NO_PROXY }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Transfer Learning Notebook Tests
        run: |
          python3 -m pip install virtualenv
          make test_tl_pyt_notebook
          make test_tl_tf_notebook
